spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
server:
  port: 53010

logging:
  level:
    root: info
    org:
      springframework : info

zuul:
  retryable: true
  ignored-services: '*'
  add-host-header: true
  sensitiveHeaders: '*'
  routes:
    #uua-service路由配置
    uaa-service.stripPrefix: false
    uaa-service.path: /uaa/**
    #order-service路由配置
    order-service.stripPrefix: false
    order-service.path: /order/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:53000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/xml
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response:
      enabled: true
